# Generated by Django 4.1 on 2022-09-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0005_alter_institution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
